# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_auto_20171111_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='updated_at',
        ),
    ]
